export const MESSAGES = {
  REGISTER_SUCCESS: 'Registration successful',
  LOGIN_SUCCESS: 'Login successful',
  LOGOUT_SUCCESS: 'Logout successful',
  EMAIL_EXISTS: 'Email already exists',
  INVALID_CREDENTIALS: 'Invalid login credentials',
  UNAUTHORIZED: 'Unauthorized access',
  VALIDATION_ERROR: 'Invalid data',
  BAD_REQUEST: 'Bad request',
  FORGOT_PASSWORD_SUCCESS: 'Password reset email has been sent',
  RESET_PASSWORD_SUCCESS: 'Password has been reset successfully',
  EMAIL_NOT_FOUND: 'Email does not exist in the system',
  INVALID_RESET_TOKEN: 'Password reset token is invalid or has expired',
  PASSWORD_RESET_EMAIL_SENT: 'Password reset email has been sent to your email address',
  SESSION_CLEARED: 'Session has been cleared successfully',
  INVALID_EMAIL_FORMAT: 'Email format is invalid',
  INVALID_PHONE_FORMAT: 'Phone number format is invalid',
  INVALID_IDENTIFY_NUMBER: 'ID number is invalid',
  INVALID_GENDER: 'Gender must be male or female',
  INVALID_AGE: 'Age must be a positive number',
  INVALID_DATE_OF_BIRTH: 'Date of birth must be valid in MM/DD/YYYY or YYYY-MM-DD format',
  PHONE_EXISTS: 'Phone number already exists',
  IDENTIFY_NUMBER_EXISTS: 'ID number already exists',
  GET_USERS_SUCCESS: 'Fetched user list successfully',
  USERS_NOT_FOUND: 'No users found',
  GET_USER_DETAIL_SUCCESS: 'Fetched user details successfully',
  USER_NOT_FOUND: 'User not found',
  ACCOUNT_INACTIVE: 'Account has been deactivated',
  ACCOUNT_LOCKED: 'Account has been locked',
  // Test Order Messages
  TEST_ORDER_CREATED_SUCCESS: 'Test order created successfully',
  TEST_ORDER_UPDATED_SUCCESS: 'Test order updated successfully',
  TEST_ORDER_DELETED_SUCCESS: 'Test order deleted successfully',
  TEST_ORDER_NOT_FOUND: 'Test order not found',
  GET_TEST_ORDERS_SUCCESS: 'Fetched test orders successfully',
  GET_TEST_ORDER_DETAIL_SUCCESS: 'Fetched test order details successfully',
  TEST_ORDERS_NOT_FOUND: 'No test orders found',
  INVALID_TEST_ORDER_STATUS: 'Invalid test order status',
  EMAIL_FORMAT_INVALID: 'Email format is invalid',
  DATE_FORMAT_INVALID: 'Date must be valid in MM/DD/YYYY or YYYY-MM-DD format'
} as const
